### ISSUE TITLE
v0.59.0 Failed to install provider

### ISSUE THREAD

**Issue by sobi3ch** [build-trust/terraform-provider-ockam#11]
```
11:16 $ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding build-trust/ockam versions matching "0.59.0"...
- Installing build-trust/ockam v0.59.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing build-trust/ockam v0.59.0: checksum list has unexpected SHA-256 hash c0dfb1fba5d6b956105f17f4c05bc1b1fdb1670633d58f27cd89158bd72ae952 (expected c4c471bfd25eff21448fb2f702e33d80e69caab1a35e886fa24654e3f4bf9db2)
```

**Comment by arbourd** [comment]
Seeing this as well, but not sure where that other hash is coming from because it's in the file, correctly. `0.1.6` works just fine.

**Comment by arbourd** [comment]
Looks like the Action ran twice. I guess it mutated the shasum file but that isn't allowed for the registry. My recommendation is to release a `v0.59.0-1` or something. 

<img width="949" alt="Screen Shot 2022-05-25 at 2 00 17 PM" src="https://user-images.githubusercontent.com/7211830/170331799-6875d0c4-ab5d-4db9-92de-be46d8975c3c.png">

**Comment by mrinalwadhwa** [comment]
Thank you both.
Terraform registry didn't pull the assets created by the second run.

There is now https://registry.terraform.io/providers/build-trust/ockam/0.59.1 to get terraform registry to pull a new release. Even the the `ockam` binary it provisions is actually `0.59.0`.

Let me know in case this doesn't fix the problem.

**Comment by arbourd** [comment]
That worked @mrinalwadhwa. This can be closed. Thanks!

**Comment by sobi3ch** [comment]
Works for me as well. Nice!
